// <auto-generated />
using BulkyBook.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyBook.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240214101613_add-image-url")]
    partial class addimageurl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyBook.Models.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2L,
                            DisplayOrder = 3,
                            Name = "Scifi"
                        },
                        new
                        {
                            Id = 3L,
                            DisplayOrder = 2,
                            Name = "History"
                        },
                        new
                        {
                            Id = 4L,
                            DisplayOrder = 4,
                            Name = "Literary Fiction"
                        },
                        new
                        {
                            Id = 5L,
                            DisplayOrder = 6,
                            Name = "Non Fiction"
                        },
                        new
                        {
                            Id = 6L,
                            DisplayOrder = 6,
                            Name = "Science and Popular Science"
                        },
                        new
                        {
                            Id = 7L,
                            DisplayOrder = 7,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 8L,
                            DisplayOrder = 9,
                            Name = "Humor"
                        },
                        new
                        {
                            Id = 9L,
                            DisplayOrder = 8,
                            Name = "Religion and Spirituality"
                        },
                        new
                        {
                            Id = 10L,
                            DisplayOrder = 10,
                            Name = "Crafts and Hobbies"
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Models.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Author = "Robert Wilson",
                            CategoryId = 2L,
                            Description = "Book is about Adventures",
                            ISBN = "12321",
                            ListPrice = 20.5,
                            Price = 19.5,
                            Price100 = 15.5,
                            Price50 = 17.5,
                            Title = "Action"
                        },
                        new
                        {
                            Id = 2L,
                            Author = "Alice Johnson",
                            CategoryId = 3L,
                            Description = "Exciting journey into the unknown",
                            ISBN = "23432",
                            ListPrice = 22.75,
                            Price = 21.25,
                            Price100 = 17.25,
                            Price50 = 19.75,
                            Title = "Adventure"
                        },
                        new
                        {
                            Id = 3L,
                            Author = "John Smith",
                            CategoryId = 2L,
                            Description = "Unraveling secrets and enigmas",
                            ISBN = "34543",
                            ListPrice = 18.989999999999998,
                            Price = 17.489999999999998,
                            Price100 = 14.49,
                            Price50 = 15.99,
                            Title = "Mystery"
                        },
                        new
                        {
                            Id = 4L,
                            Author = "Emily Brown",
                            CategoryId = 5L,
                            Description = "Magical realms and mythical creatures",
                            ISBN = "45654",
                            ListPrice = 25.989999999999998,
                            Price = 24.489999999999998,
                            Price100 = 21.489999999999998,
                            Price50 = 22.989999999999998,
                            Title = "Fantasy"
                        },
                        new
                        {
                            Id = 5L,
                            Author = "David Jones",
                            CategoryId = 4L,
                            Description = "Exploring futuristic worlds and technology",
                            ISBN = "56765",
                            ListPrice = 29.989999999999998,
                            Price = 28.489999999999998,
                            Price100 = 25.489999999999998,
                            Price50 = 26.989999999999998,
                            Title = "Science Fiction"
                        },
                        new
                        {
                            Id = 6L,
                            Author = "Sophia Lee",
                            CategoryId = 3L,
                            Description = "Heartwarming love stories",
                            ISBN = "67876",
                            ListPrice = 15.949999999999999,
                            Price = 14.449999999999999,
                            Price100 = 11.449999999999999,
                            Price50 = 12.949999999999999,
                            Title = "Romance"
                        },
                        new
                        {
                            Id = 7L,
                            Author = "Michael White",
                            CategoryId = 2L,
                            Description = "Nerve-wracking suspense and excitement",
                            ISBN = "78987",
                            ListPrice = 21.5,
                            Price = 20.0,
                            Price100 = 17.0,
                            Price50 = 18.5,
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = 8L,
                            Author = "Elizabeth Taylor",
                            CategoryId = 6L,
                            Description = "Journeys through historical events and periods",
                            ISBN = "89098",
                            ListPrice = 27.75,
                            Price = 26.25,
                            Price100 = 23.25,
                            Price50 = 24.75,
                            Title = "Historical Fiction"
                        },
                        new
                        {
                            Id = 9L,
                            Author = "Thomas Harris",
                            CategoryId = 3L,
                            Description = "Terrifying tales of fear and horror",
                            ISBN = "90109",
                            ListPrice = 19.989999999999998,
                            Price = 18.489999999999998,
                            Price100 = 15.49,
                            Price50 = 16.989999999999998,
                            Title = "Horror"
                        },
                        new
                        {
                            Id = 10L,
                            Author = "Anna Miller",
                            CategoryId = 8L,
                            Description = "Inspirational life stories",
                            ISBN = "01210",
                            ListPrice = 16.5,
                            Price = 15.0,
                            Price100 = 12.0,
                            Price50 = 13.5,
                            Title = "Biography"
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Models.Products.Product", b =>
                {
                    b.HasOne("BulkyBook.Models.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
